Added support for MemoryDB, updated README.MD, increased incremental traffic, fixed an issue with check_replication_runs, added memory optimization

diff --git a/glue/bin/cqlreplicator b/glue/bin/cqlreplicator
--- a/glue/bin/cqlreplicator
+++ b/glue/bin/cqlreplicator
@@ -18,7 +18,7 @@ WRITETIME_COLUMN="None"
 TTL_COLUMN="None"
 S3_LANDING_ZONE=""
 COOLING_PERIOD=5
-INCR_TRAFFIC=120
+INCR_TRAFFIC=240
 JOBS=()
 DISCOVERED_TOTAL=0
 REPLICATED_TOTAL=0
@@ -50,7 +50,8 @@ MAVEN_REPO=https://repo1.maven.org/maven2
 ARTIFACTS=("/com/datastax/spark/spark-cassandra-connector-assembly_2.12/3.4.1/spark-cassandra-connector-assembly_2.12-3.4.1.jar"
 "/io/vavr/vavr/0.10.4/vavr-0.10.4.jar" "/io/github/resilience4j/resilience4j-retry/1.7.1/resilience4j-retry-1.7.1.jar"
 "/io/github/resilience4j/resilience4j-core/1.7.1/resilience4j-core-1.7.1.jar"
-"/software/aws/mcs/aws-sigv4-auth-cassandra-java-driver-plugin/4.0.9/aws-sigv4-auth-cassandra-java-driver-plugin-4.0.9.jar")
+"/software/aws/mcs/aws-sigv4-auth-cassandra-java-driver-plugin/4.0.9/aws-sigv4-auth-cassandra-java-driver-plugin-4.0.9.jar"
+"/redis/clients/jedis/4.4.6/jedis-4.4.6.jar")
 
 set +x
 
@@ -117,12 +118,12 @@ function check_replication_runs() {
    local tile
    local rs
    tile=$1
-   rs=$(aws glue get-job-runs --job-name CQLReplicator --region "$AWS_REGION" --query 'JobRuns[?JobRunState==`RUNNING`] | [].Arguments | [?"--PROCESS_TYPE"==`replication`]' | jq '.[0]["--SOURCE_TBL"] == "'"$SOURCE_TBL"'" and .[0]["--SOURCE_KS"] == "'"$SOURCE_KS"'" and .[]["--TILE"] == "'"$tile"'"' | grep true)
-
-   if [[ $rs == "true" ]]; then
-     #log "ERROR: Replication job is already running per tile $tile for" $SOURCE_KS.$SOURCE_TBL
+   rs=$(aws glue get-job-runs --job-name CQLReplicator --region "$AWS_REGION" --query 'JobRuns[?JobRunState==`RUNNING`] | [].Arguments | [?"--PROCESS_TYPE"==`replication`]' | jq '.[] | select(."--TILE"=="'"$tile"'" and ."--SOURCE_TBL"=="'"$SOURCE_TBL"'" and ."--SOURCE_KS"=="'"$SOURCE_KS"'")')
+   if [[ -n "${rs}" ]]; then
+     log "ERROR: Replication job is already running per tile $tile for" $SOURCE_KS.$SOURCE_TBL
+     log "$rs"
      return 1
-   fi
+  fi
    return 0
 }
 
@@ -150,6 +151,22 @@ function progress {
   if [ "$total" -eq "$current" ]; then
       echo -e " - COMPLETED"
   fi
+}
+
+function uploader_helper() {
+  local artifact_name="$1"
+  local curr_pos=$2
+  local next_pos=$3
+  local final_pos=$4
+  progress $curr_pos $final_pos "Uploading $artifact_name                       "
+      if ls "$path_to_conf/$artifact_name" > /dev/null
+        then
+          progress $next_pos $final_pos "Uploading $artifact_name                  "
+          aws s3 cp "$path_to_conf"/"$artifact_name" "$S3_LANDING_ZONE"/artifacts/"$artifact_name" > /dev/null
+        else
+          log "ERROR: $path_to_conf/$artifact_name not found"
+          exit 1
+        fi
 }
 
 function barrier() {
@@ -247,25 +264,14 @@ function Init {
   local path_to_scala
   path_to_conf=$(ls -d "$BASE_FOLDER" | sed 's/bin/conf/g')
   path_to_scala=$(ls -d "$BASE_FOLDER" | sed 's/bin/sbin/g')"/$TARGET_TYPE"
-  progress 0 5 "Uploading KeyspacesConnector.conf                    "
 
-  if ls "$path_to_conf/KeyspacesConnector.conf" > /dev/null
-  then
-    progress 1 5 "Uploading KeyspacesConnector.conf                  "
-    aws s3 cp "$path_to_conf"/KeyspacesConnector.conf "$S3_LANDING_ZONE"/artifacts/KeyspacesConnector.conf > /dev/null
-  else
-    log "ERROR: $path_to_conf/KeyspacesConnector.conf not found"
-    exit 1
+  if [[ $TARGET_TYPE == "memorydb" ]]; then
+    uploader_helper "RedisConnector.conf" 0 1 5
   fi
-
-  if ls "$path_to_conf/CassandraConnector.conf" > /dev/null
-  then
-    aws s3 cp "$path_to_conf"/CassandraConnector.conf "$S3_LANDING_ZONE"/artifacts/CassandraConnector.conf > /dev/null
-    progress 2 5 "Uploading CassandraConnector.conf                  "
-  else
-    log "ERROR: $path_to_conf/CassandraConnector.conf not found"
-    exit 1
+  if [[ $TARGET_TYPE == "keyspaces" ]]; then
+    uploader_helper "KeyspacesConnector.conf" 0 1 5
   fi
+  uploader_helper "CassandraConnector.conf" 1 2 5
 
   local glue_bucket_artifacts=s3://aws-glue-assets-"$AWS_ACCOUNT"-"$AWS_REGION"
   if aws s3 ls "$glue_bucket_artifacts"/scripts/ > /dev/null
@@ -311,13 +317,13 @@ function Init {
            --worker-type "G.1X" \
            --connections "Connections=$glue_conn_name" \
            --command "Name=gluestreaming,ScriptLocation=$glue_bucket_artifacts/scripts/CQLReplicator.scala" \
-           --execution-property '{"MaxConcurrentRuns": 16}' \
+           --execution-property '{"MaxConcurrentRuns": 32}' \
            --max-retries 1 \
            --region "$AWS_REGION" \
            --default-arguments '{
                "--job-language":"scala",
-               "--extra-jars":"'$S3_LANDING_ZONE'/artifacts/spark-cassandra-connector-assembly_2.12-3.4.1.jar,'$S3_LANDING_ZONE'/artifacts/resilience4j-retry-1.7.1.jar,'$S3_LANDING_ZONE'/artifacts/resilience4j-core-1.7.1.jar,'$S3_LANDING_ZONE'/artifacts/vavr-0.10.4.jar,'$S3_LANDING_ZONE'/artifacts/aws-sigv4-auth-cassandra-java-driver-plugin-4.0.9.jar",
-               "--conf":"spark.files='$S3_LANDING_ZONE'/artifacts/KeyspacesConnector.conf,'$S3_LANDING_ZONE'/artifacts/CassandraConnector.conf --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.sql.extensions=com.datastax.spark.connector.CassandraSparkExtensions",
+               "--extra-jars":"'$S3_LANDING_ZONE'/artifacts/jedis-4.4.6.jar,'$S3_LANDING_ZONE'/artifacts/spark-cassandra-connector-assembly_2.12-3.4.1.jar,'$S3_LANDING_ZONE'/artifacts/resilience4j-retry-1.7.1.jar,'$S3_LANDING_ZONE'/artifacts/resilience4j-core-1.7.1.jar,'$S3_LANDING_ZONE'/artifacts/vavr-0.10.4.jar,'$S3_LANDING_ZONE'/artifacts/aws-sigv4-auth-cassandra-java-driver-plugin-4.0.9.jar",
+               "--conf":"spark.files='$S3_LANDING_ZONE'/artifacts/KeyspacesConnector.conf,'$S3_LANDING_ZONE'/artifacts/CassandraConnector.conf --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.sql.extensions=com.datastax.spark.connector.CassandraSparkExtensions --conf spark.kryoserializer.buffer.max=128m --conf spark.rdd.compress=true --conf spark.cleaner.periodicGC.interval=1min",
                "--class":"GlueApp"
            }' > /dev/null
    fi
@@ -332,13 +338,13 @@ function Init {
           --number-of-workers 2 \
           --worker-type "G.1X" \
           --command "Name=gluestreaming,ScriptLocation=$glue_bucket_artifacts/scripts/CQLReplicator.scala" \
-          --execution-property '{"MaxConcurrentRuns": 16}' \
+          --execution-property '{"MaxConcurrentRuns": 32}' \
           --max-retries 1 \
           --region "$AWS_REGION" \
           --default-arguments '{
               "--job-language":"scala",
-              "--extra-jars":"'$S3_LANDING_ZONE'/artifacts/spark-cassandra-connector-assembly_2.12-3.4.1.jar,'$S3_LANDING_ZONE'/artifacts/resilience4j-retry-1.7.1.jar,'$S3_LANDING_ZONE'/artifacts/resilience4j-core-1.7.1.jar,'$S3_LANDING_ZONE'/artifacts/vavr-0.10.4.jar,'$S3_LANDING_ZONE'/artifacts/aws-sigv4-auth-cassandra-java-driver-plugin-4.0.9.jar",
-              "--conf":"spark.files='$S3_LANDING_ZONE'/artifacts/KeyspacesConnector.conf,'$S3_LANDING_ZONE'/artifacts/CassandraConnector.conf --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.sql.extensions=com.datastax.spark.connector.CassandraSparkExtensions",
+              "--extra-jars":"'$S3_LANDING_ZONE'/artifacts/jedis-4.4.6.jar,'$S3_LANDING_ZONE'/artifacts/spark-cassandra-connector-assembly_2.12-3.4.1.jar,'$S3_LANDING_ZONE'/artifacts/resilience4j-retry-1.7.1.jar,'$S3_LANDING_ZONE'/artifacts/resilience4j-core-1.7.1.jar,'$S3_LANDING_ZONE'/artifacts/vavr-0.10.4.jar,'$S3_LANDING_ZONE'/artifacts/aws-sigv4-auth-cassandra-java-driver-plugin-4.0.9.jar",
+              "--conf":"spark.files='$S3_LANDING_ZONE'/artifacts/KeyspacesConnector.conf,'$S3_LANDING_ZONE'/artifacts/CassandraConnector.conf --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.sql.extensions=com.datastax.spark.connector.CassandraSparkExtensions --conf spark.kryoserializer.buffer.max=128m --conf spark.rdd.compress=true --conf spark.cleaner.periodicGC.interval=1min",
               "--class":"GlueApp"
               }' > /dev/null
   fi
@@ -592,7 +598,7 @@ while (( "$#" )); do
       #You can increase this value to reduce traffic pressure
       COOLING_PERIOD="$INCR_TRAFFIC"
       log "Incremental traffic for the historical workload is enabled"
-      log "Cooling period:" $COOLING_PERIOD
+      log "Incremental period: $COOLING_PERIOD seconds"
       shift 1
       ;;
     --offload-large-objects|-x)
