Moved banner outside the cqlreplicator. Fixed double String to JValue conversions

diff --git a/glue/bin/cqlreplicator b/glue/bin/cqlreplicator
--- a/glue/bin/cqlreplicator
+++ b/glue/bin/cqlreplicator
@@ -39,7 +39,7 @@ declare -A params=(
     [DEFAULT_WORKLOAD_TYPE]=continuous
     [GLUE_TYPE]=gluestreaming
     [WCU_TRAFFIC]=0
-    [DEFAULT_ROWS_PER_SECOND]=2000
+    [DEFAULT_ROWS_PER_SECOND]=3500
     [PROCESS_RUNNING]=false
     [TIME_SCHEDULE]=""
 )
@@ -62,25 +62,18 @@ PCU="-"
 PPS=2
 
 set +x
+
 # The Art
 GREEN='\033[1;32m'
 NC='\033[0m' # No Color
-cat <(echo -e "${GREEN}") - <(echo -e "${NC}") << "EOF"
-    ___ ___  _     ____            _ _           _
-  / ___/ _ \| |   |  _ \ ___ _ __ | (_) ___ __ _| |_ ___  _ __
- | |  | | | | |   | |_) / _ \ '_ \| | |/ __/ _` | __/ _ \| '__|
- | |__| |_| | |___|  _ <  __/ |_) | | | (_| (_| | || (_) | |
-  \____\__\_\_____|_| \_\___| .__/|_|_|\___\__,_|\__\___/|_|
-                            |_|
-·······································································
-:     __          _______   _____           _____                     :
-:    /\ \        / / ____| |  __ \         / ____|                    :
-:   /  \ \  /\  / / (___   | |__) | __ ___| (___   ___ _ ____   _____ :
-:  / /\ \ \/  \/ / \___ \  |  ___/ '__/ _ \\___ \ / _ \ '__\ \ / / _ \:
-: / ____ \  /\  /  ____) | | |   | | | (_) |___) |  __/ |   \ V /  __/:
-:/_/    \_\/  \/  |_____/  |_|   |_|  \___/_____/ \___|_|    \_/ \___|:
-·······································································
-EOF
+BANNER_FILE="banner.txt"
+if [ ! -f "$BANNER_FILE" ]; then
+    echo "Error: Banner file not found!"
+    exit 1
+fi
+BANNER=$(cat "$BANNER_FILE" || echo "Default Banner")
+echo -e "${GREEN}${BANNER}${NC}"
+
 # Preflight checks
 # Check Bash version
 if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
@@ -926,32 +919,35 @@ function Start_Discovery {
 
 function Resize_Cluster {
   check_input "${params[SOURCE_KS]}" "Error: source keyspace name is empty, must be provided"
-    check_input "${params[SOURCE_TBL]}" "Error: source table name is empty, must be provided"
-    check_input "${params[S3_LANDING_ZONE]}" "Error: landing zone must be provided"
-    check_input "${params[AWS_REGION]}" "Error: aws region must be provided"
-    check_input "${params[TILES]}" "Error: new number of tiles should be provided"
-    log_info "SOURCE:" "${params[SOURCE_KS]}"."${params[SOURCE_TBL]}"
-    log_info "LANDING ZONE:" "${params[S3_LANDING_ZONE]}"
-    log_info "WORKER_TYPE: ${params[WORKER_TYPE]}"
-    log_info "Resizing the tiles. The new size is ${params[TILES]}"
-    check_sampler_runs resize
-    if [ "${params[PROCESS_RUNNING]}" = false ]; then
-      aws s3 cp "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/primaryKeys" \
+  check_input "${params[SOURCE_TBL]}" "Error: source table name is empty, must be provided"
+  check_input "${params[S3_LANDING_ZONE]}" "Error: landing zone must be provided"
+  check_input "${params[AWS_REGION]}" "Error: aws region must be provided"
+  check_input "${params[TILES]}" "Error: new number of tiles should be provided"
+  log_info "SOURCE:" "${params[SOURCE_KS]}"."${params[SOURCE_TBL]}"
+  log_info "LANDING ZONE:" "${params[S3_LANDING_ZONE]}"
+  log_info "WORKER_TYPE: ${params[WORKER_TYPE]}"
+  log_warn "The replication process for ${params[SOURCE_KS]}.${params[SOURCE_TBL]} is going to be resized"
+  log_warn "Before proceeding the replication process must be stopped"
+  log_info "Resizing the tiles. The new size is ${params[TILES]}"
+  confirm "<=== Do you want to continue? ===> "
+  check_sampler_runs resize
+  if [ "${params[PROCESS_RUNNING]}" = false ]; then
+    aws s3 cp "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/primaryKeys" \
                     "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/primaryKeysCopy" \
                     --recursive --region "${params[AWS_REGION]}" >/dev/null
       # Check if primaryKeysCopy exists if the prefix doesn't exists return error and exit
-      if aws s3 ls "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/primaryKeysCopy/" --region "${params[AWS_REGION]}" > /dev/null; then
-        log_info "The copy has been created"
-      else
-        log_error "No copy found in ${params[S3_LANDING_ZONE]}"
-        exit 1
-      fi
-      log_info "Removing the primary keys and stats"
-      aws s3 rm "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/primaryKeys" \
-                    --recursive --region "${params[AWS_REGION]}" >/dev/null
-      aws s3 rm "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/stats" \
-                    --recursive --region "${params[AWS_REGION]}" >/dev/null
-      rs=$(aws glue start-job-run --job-name "${params[JOB_NAME]}${params[DEFAULT_ENV]}" --worker-type "G.1X" --number-of-workers $(( ${params[TILES]} + 1 )) --region "${params[AWS_REGION]}" --arguments '{
+    if aws s3 ls "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/primaryKeysCopy/" --region "${params[AWS_REGION]}" > /dev/null; then
+      log_info "The copy has been created"
+    else
+      log_error "No copy found in ${params[S3_LANDING_ZONE]}"
+      exit 1
+    fi
+    log_info "Removing the primary keys and stats"
+    aws s3 rm "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/primaryKeys" \
+                  --recursive --region "${params[AWS_REGION]}" >/dev/null
+    aws s3 rm "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/stats" \
+                  --recursive --region "${params[AWS_REGION]}" >/dev/null
+    rs=$(aws glue start-job-run --job-name "${params[JOB_NAME]}${params[DEFAULT_ENV]}" --worker-type "G.1X" --number-of-workers $(( ${params[TILES]} + 1 )) --region "${params[AWS_REGION]}" --arguments '{
             "--PROCESS_TYPE":"resize",
             "--TILE":"0",
             "--TOTAL_TILES":"'${params[TILES]}'",
@@ -968,23 +964,23 @@ function Resize_Cluster {
             "--REPLAY_LOG":"'${params[REPLAY_LOG]}'",
             "--TTL_COLUMN":"'${params[TTL_COLUMN]}'",
             "--WORKLOAD_TYPE":"'${params[DEFAULT_WORKLOAD_TYPE]}'"}' --output text)
-      params[PROCESS_RUNNING]=true
-      local delay=0.1
-      local spinstr='|/-\'
-      output="Glue job $rs is running. Resizing in progress..."
-      sleep 20
-      while [ "${params[PROCESS_RUNNING]}" = true ]; do
-        local temp=${spinstr#?}
-        printf "\r%s [%c]  " "$output" "$spinstr"
-        local spinstr=$temp${spinstr%"$temp"}
-        sleep $delay
-        check_sampler_runs resize
-      done
+    params[PROCESS_RUNNING]=true
+    local delay=0.1
+    local spinstr='|/-\'
+    output="Glue job $rs is running. Resizing in progress..."
+    sleep 20
+    while [ "${params[PROCESS_RUNNING]}" = true ]; do
+      local temp=${spinstr#?}
+      printf "\r%s [%c]  " "$output" "$spinstr"
+      local spinstr=$temp${spinstr%"$temp"}
+      sleep $delay
+      check_sampler_runs resize
+    done
       printf "\r%s    \n" "$output"
       log_info "Removing copy of the primary keys"
       aws s3 rm "${params[S3_LANDING_ZONE]}/${params[SOURCE_KS]}/${params[SOURCE_TBL]}/primaryKeysCopy" \
                     --recursive --region "${params[AWS_REGION]}" >/dev/null
-    fi
+  fi
 }
 
 function Kill_Replication {
